---
title: "R Notebook"
output: html_notebook
---
Data frames
```{r}
mtcars
head(mtcars)
tail(mtcars)


str(mtcars)


name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

planeta_df <- data.frame(name, type, diameter, rotation, rings)
planeta_df

```
```{r}
planeta_df [1,3]
planeta_df [4,]
planeta_df [1:5,]
planeta_df [1:5,"rotacion"]
```
```{r}
planeta_df[1:5,c("rotation","type")]


```
```{r}
planeta_df$name

rings_vector <- planeta_df$rings
rings_vector
planeta_df[rings_vector,]

```


```{r}
subset(planeta_df, subset = diameter< 1)
```

Sorting 

```{r}
a <- c(100,10,1000)

order(a)

a[order(a)]

b <- a[order(a)]
b

position <- order(planeta_df$diameter)

position


planeta_df[position,]

planeta_df[,1]
rings_vector

planeta_df[1,]


```


Lists

```{r}

my_vector <- 1:10
my_matrix <- matrix(1:9, ncol = 3)
my_df <- planeta_df[1:4,]
my_list <- list (my_vector, my_matrix, my_df)
my_list
```

Creating a named list
```{r}

names(my_list) <- c("vector", "matrix", "dataframe")
my_list
```

Selecting elements from a list

```{r}

my_list[[1]][4]
my_list[[2]][2,]
my_list[[3]][2:3,1:2]
```


